program: FINAL_PIPELINE_AND_TRAINING/XGB_training_basic.py
method: bayes
entity: edema_pred_ml
project: basic_comparison_8hr_sweep
metric:
  name: xgb mgb mean AUROC
  goal: maximize 
parameters:
  lookback_hours:
    values: [24]
  lookahead_hours:
    values: [8]
  no_transition_weighting:
    min: 0.45
    max: 0.95
  learning_rate:
    min: 0.001
    max: 0.1
  max_depth:
    min: 2
    max: 8
  min_child_weight:
    min: 1
    max: 8
  gamma:
    min: 0.0
    max: 3.0
  subsample:
    min: 0.65
    max: 0.95
  reg_lambda:
    min: 2.0
    max: 8.0
  reg_alpha:
    min: 0.0
    max: 4.0
  
