program: FINAL_PIPELINE_AND_TRAINING/XGB_training_multi.py
method: bayes
entity: edema_pred_ml
project: final_24hr_sweep
metric:
  name: xgb mgb filtered mean AUROC
  goal: maximize 
parameters:
  lookback_hours:
    values: [24]
  lookahead_hours:
    values: [24]
  no_transition_weighting:
    min: 0.45
    max: 0.6
  learning_rate:
    min: 0.001
    max: 0.04
  max_depth:
    min: 5
    max: 7
  min_child_weight:
    min: 1
    max: 6
  gamma:
    min: 0.0
    max: 3.0
  subsample:
    min: 0.7
    max: 0.9
  reg_lambda:
    min: 3.0
    max: 8.0
  reg_alpha:
    min: 0.0
    max: 4.0
  
